name: Playwright Tests

on:
  workflow_run:
    workflows: ["Hexo Build and Deploy"]  # Trigger on successful completion of Hexo workflow
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install  # Ensure browsers are installed

      - name: Run Playwright Tests
        run: |
          npx playwright test --trace on  # Run tests with tracing enabled for debugging
