name: Playwright Tests

on:
  workflow_run:
    workflows: ["Deploy Hexo to GitHub Pages"]  # Use the name of your Hexo workflow
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if the Hexo workflow succeeded
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the appropriate Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps  # Install all Playwright dependencies and browsers

    - name: Run Playwright Tests
      run: npx playwright test
